/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 12
#define YY_END_OF_BUFFER 13
static yyconst short int yy_accept[280] =
    {   0,
        0,    0,   13,   11,   12,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,    0,    0,    0,    0,
        0,    0,    0,    0,    2,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    2,    2,
        2,    2,    2,    0,    0,    0,    6,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    2,    2,    2,    2,    2,    0,    0,    0,

        0,    9,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    3,    0,    0,    0,    0,    0,    0,    2,
        2,    2,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    2,    2,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    4,    0,
        0,    0,    0,    0,    2,    0,    0,    0,    7,    0,
        5,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    2,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    2,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    2,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   10,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    1,    0,    8,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    1,    5,    1,    1,    6,    1,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,    1,   16,   17,
       18,   19,    1,    1,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
        1,    1,    1,   21,    1,    1,   22,   23,   24,   25,

       26,   27,   28,   29,   30,   20,   20,   31,   20,   32,
       33,   20,   20,   34,   35,   36,   37,   20,   38,   20,
       20,   20,   39,   40,    1,   41,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[42] =
    {   0,
        1,    1,    2,    3,    1,    4,    5,    6,    7,    4,
        8,    4,    9,    4,   10,   11,   12,   13,   12,   14,
        4,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,    1,    4,
        4
    } ;

static yyconst short int yy_base[321] =
    {   0,
        0,    0,  794, 1133, 1133,   39,  763,  778,   68,  107,
       14,   15,   19,   22,   23,  762,   70,  761,  760,   24,
       29,   30,   32,  756,  146,  185,  784,  757,   46,   47,
       50,   54,   85,   62,   61,   73,   77,   67,   89,   76,
       91,  761,    0,    0,    0,    0,  755,  750,  751,  748,
      746,  775,  224,   95,  103,  101,  109,  130,  774,  263,
      106,  110,  111,  128,  124,  302,  114,  744,  751,  734,
      735,  729,  728,  341,  756,  380, 1133,  134,  182,  164,
      755,  198,  419,  754,  458,  187,  178,  179,  169,  497,
      753,  718,  720,  730,   23,    0,  724,  748,  536,  183,

      211, 1133,  239,  732,  243,  746,  730,  228,  744,  221,
      743,    0, 1133,  575,  245,  193,  252,  614,  720,  713,
      707,  738,  737,  653,  709,  711,  733,  151,  276,  692,
      279,  721,  731,  277,  291,  246,  729,  310,  316,  319,
      703,  187,  695,  282,  215,  294,  251,    0,  297,  692,
      687,  687,  683,  681,  322,  760,  338,  345, 1133,  238,
      710,  355,  377,   64,  679,  331,  708,  298, 1133,  307,
     1133,  688,  672,  675,  671,  674,  263,  360,  687,  394,
      696,  679,  388,  368,    0,  656,  679,  431,  647,  641,
      638,  655,  625,  399,  641,  357,  427,  625,  599,  509,

      594,  513,  605,  585,  570,  552,  583,  392,  570,  540,
      569,  522,  367,  328,  416,  436,  442,  525,  522,  531,
      526,  424,  498,  433,  538,  443,  337,  499,  366, 1133,
      296,  463,  494,  502,  567,  428,  423,  424,  394,  385,
      511,  501,  517, 1133,  520, 1133,  395,  370,  354,  340,
      334,  550,  518,  557,  305,  305,  296,  306,  248,  572,
      220,  193,  189,  563,  141,  596,   89,  602,  611,  564,
      622,  626,  628,  638,  640,  668,  639,  669, 1133,  461,
      800,  463,  813,  588,  826,  607,  839,  852,  865,  878,
      638,  891,  664,  671,  904,  917,  930,  943,  673,  956,

      682,  684,   93,  969,  687,  982,  995, 1008, 1014,  688,
     1027, 1040, 1053, 1066,  689, 1079,  690, 1092, 1105, 1118
    } ;

static yyconst short int yy_def[321] =
    {   0,
      279,    1,  279,  279,  279,  280,  279,  279,  281,  281,
       10,   10,   10,   10,   10,   10,  280,   10,   10,   10,
       10,   10,   10,  279,  279,  279,  282,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,  279,   25,   25,   25,   25,   25,   25,   25,   25,
       25,  282,  283,   10,   10,   10,   10,   26,  284,  285,
       10,   10,   10,   10,   10,  285,   10,  279,   25,   25,
       25,   25,   25,  279,  286,  283,  279,   10,   10,   10,
      284,  287,  288,  282,  279,   66,   10,   10,   10,  289,
       66,  279,   25,   25,   25,   25,   25,  286,  290,   10,

       26,  279,  279,  279,  287,  291,  279,  292,  293,   26,
      294,   85,  279,  288,   10,   10,  295,  289,  279,   25,
       25,   25,   74,  290,  101,  279,  291,  296,  279,  279,
      292,  297,  294,  298,  292,   26,  299,  279,  295,  295,
      279,   25,   25,  279,  279,  279,  296,  130,  279,  279,
      279,  279,  279,  279,   74,  297,  279,  298,  279,  135,
      299,  300,  295,  279,   25,  279,  301,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  135,  279,  279,  300,
      302,  279,  295,  279,  303,   25,  301,  304,  279,  279,
      279,  305,  279,  306,  302,  307,  308,  309,   25,  279,

      279,  304,  310,  279,  279,  279,  305,  311,  305,  312,
      279,  135,  279,  279,  307,  313,  295,  279,  309,   25,
      310,  314,  279,  279,  279,  311,  305,  315,  279,  279,
      279,  279,  279,  314,  279,  279,  279,  279,  279,  279,
      311,  316,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  311,  279,  316,  279,  279,  279,  317,  279,  311,
      279,  279,  317,  318,  317,  319,  279,  279,  318,  317,
      305,  311,  318,  318,  318,  320,  317,  318,    0,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,

      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279
    } ;

static yyconst short int yy_nxt[1175] =
    {   0,
        4,    5,    6,    4,    7,    4,    4,    4,    4,    4,
        4,    4,    4,    8,    4,    4,    4,    4,    4,    9,
        4,    9,    9,   10,   11,   12,   13,    9,    9,   14,
       15,    9,    9,    9,    9,    9,    9,   16,    4,    4,
        4,   17,   28,   28,  121,   31,   30,   28,   33,   32,
       28,   28,   28,   34,   97,   35,   38,   28,   28,   39,
       28,   40,   19,   20,   41,   21,  184,   54,   22,   23,
       26,   27,   17,   27,   28,   28,   27,   27,   28,   27,
      185,   27,   28,   55,   56,   27,   57,   58,   27,   28,
       28,   59,   61,   19,   20,   28,   21,   60,   63,   22,

       23,   28,   62,   64,   28,   28,  198,   27,   27,   26,
       27,   66,   27,   28,  258,   27,   27,   28,   27,   28,
       27,   65,   67,   28,   27,   78,   79,   27,   60,   28,
       80,   28,   58,   86,   28,   29,   59,   28,   28,   28,
       87,   91,   28,  270,   66,   89,   27,   27,   43,   44,
       88,   44,   28,  145,   44,   44,   28,   44,  146,   44,
       45,   46,   28,   44,  100,   45,   44,   45,   45,   47,
       48,   45,   49,   45,   45,   50,   51,   45,   45,   45,
       45,   45,   45,   45,  101,   44,   44,   26,   27,  114,
       27,  263,   28,   27,   27,   84,   27,   28,   27,   60,

      103,  104,   27,  115,   66,   27,   28,   28,   60,  116,
       28,   28,   96,  125,  106,  107,  106,  145,   66,   73,
      102,   28,  146,  110,   27,   27,   74,   75,  258,   75,
      129,  111,   75,   75,  130,   75,  113,   75,  111,   77,
      126,  103,  104,  113,   75,  103,  104,  136,  136,  102,
      267,  137,  137,  145,  138,  106,  107,  106,  146,  106,
      107,  106,  111,   75,   75,   83,   27,  113,   27,  177,
      131,   84,   27,   28,   27,  265,   27,   28,  129,  157,
       27,  129,  130,   27,  166,  130,  111,  111,  167,  111,
      194,  113,  159,  129,  113,  131,  168,  130,  243,  170,

      168,  111,   27,   27,   90,   27,  113,   27,  263,  170,
       27,   27,  138,   27,  244,   27,   28,  262,  138,   27,
      111,  138,   27,  160,  155,  113,  111,  261,  130,  111,
      229,  113,  169,  166,  113,  171,  169,  167,  258,  207,
      157,   27,   27,   74,   75,  171,   75,  157,  111,   75,
       75,  163,   75,  159,   75,  111,   77,  178,  179,  213,
      159,   75,  178,  179,  214,  259,  230,  241,  229,  213,
      184,  181,  182,  181,  214,  258,  181,  182,  181,  138,
       75,   75,   74,   75,  185,   75,  257,  111,   75,   75,
      138,   75,  113,   75,  224,   77,  178,  179,  111,  149,

       75,  210,  225,  113,  230,  130,  256,  211,  183,  111,
      181,  182,  181,  131,  113,  197,  255,  251,  213,   75,
       75,   83,   27,  214,   27,  250,  232,   84,   27,  216,
       27,  233,   27,  200,  201,  224,   27,  111,  216,   27,
      149,  139,  113,  225,  138,  224,  111,  203,  204,  203,
      149,  113,  111,  225,  249,  248,  247,  113,   27,   27,
      110,   27,   18,   27,   53,  232,   27,   27,  111,   27,
      233,   27,  112,  113,   18,   27,   53,  112,   27,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  245,   27,   27,   90,

       27,  228,   27,  253,  232,   27,   27,  130,   27,  233,
       27,  200,  201,  224,   27,  200,  201,   27,  149,  243,
      253,  225,  245,  192,  130,  203,  204,  203,  221,  203,
      204,  203,  246,  143,  218,  244,   27,   27,  123,   75,
      235,   75,  210,  252,   75,   75,  130,   75,  211,   75,
      111,   77,  224,  231,  131,  113,   75,  149,  246,  253,
      225,  236,  237,  130,  238,  268,  263,  239,  240,  235,
      149,  228,  227,  225,  224,   75,   75,   83,   27,  149,
       27,  260,  225,   84,   27,  207,   27,  192,   27,   82,
      236,  237,   27,  238,  273,   27,  239,  240,  271,  266,

      223,   82,  203,  149,  268,  135,  225,  221,   99,  149,
      226,  203,  225,  268,   27,   27,   90,   27,  149,   27,
       99,  225,   27,   27,  271,   27,  220,   27,  224,  149,
      268,   27,  225,  149,   27,  149,  225,  218,  225,  128,
      268,  277,  268,  195,  140,  149,  149,  149,  225,  225,
      225,  128,  209,   27,   27,  123,   75,  207,   75,  206,
      274,   75,   75,  205,   75,  132,   75,  276,   77,  275,
      277,  268,  134,   75,  162,  149,  149,  132,  225,  225,
      192,  187,  269,  188,  134,  196,  162,  199,  208,  222,
      242,  264,   75,   75,  148,  188,  181,  196,  195,  149,

      208,  222,  242,  264,  181,  193,  192,  191,  190,  189,
      187,  186,  161,  176,  175,  150,  151,  174,  152,  173,
      172,  153,  154,  155,   75,  165,   75,  130,  164,   75,
       75,  161,   75,  133,   75,  127,   77,  144,  279,  123,
      143,   75,   96,  142,  141,  133,  109,  106,  127,  106,
       98,  122,  120,   96,  119,  118,  109,   81,   98,   97,
       75,   75,  155,   75,   96,   75,  130,   95,   75,   75,
       94,   75,   93,   75,   92,   77,   81,   52,   73,   72,
       75,   71,   70,   69,   68,   28,   52,   42,   37,   28,
       36,   25,   24,  279,  279,  279,  279,  279,  279,   75,

       75,   28,   28,   28,  279,  279,   28,  279,  279,   28,
      279,  279,   28,   28,   76,   76,   76,  279,  279,   76,
      279,  279,   76,   76,  279,  279,   76,   85,   85,   85,
      279,  279,   85,  279,  279,   85,  279,  279,   85,   85,
      105,  105,  279,  279,  279,  279,  279,  279,  105,  279,
      105,  105,  105,  108,  108,  108,  279,  279,  108,  279,
      279,  279,  279,  279,  108,  108,  117,  117,  117,  279,
      279,  117,  279,  279,  279,  279,  279,  117,  117,  124,
      124,  124,  279,  279,  124,  279,  279,  124,  124,  279,
      279,  124,  131,  279,  279,  131,  279,  279,  131,  279,

      131,  131,  279,  279,  131,  139,  279,  279,  279,  279,
      279,  139,  279,  139,  139,  279,  279,  139,  147,  279,
      279,  279,  147,  279,  279,  279,  147,  279,  279,  279,
      147,  156,  156,  156,  156,  279,  156,  279,  279,  156,
      156,  279,  279,  156,  158,  279,  279,  279,  279,  279,
      158,  279,  158,  158,  279,  279,  158,  180,  180,  279,
      279,  279,  279,  279,  279,  180,  279,  180,  180,  180,
      202,  202,  279,  279,  279,  279,  279,  279,  202,  279,
      202,  202,  202,  212,  279,  279,  212,  279,  212,  212,
      279,  212,  212,  279,  279,  212,  215,  279,  279,  279,

      215,  279,  279,  279,  215,  279,  279,  279,  215,  217,
      279,  279,  279,  279,  279,  217,  279,  217,  217,  279,
      279,  217,  219,  219,  279,  279,  279,  219,  226,  279,
      279,  279,  226,  279,  226,  279,  226,  279,  279,  279,
      226,  108,  279,  279,  108,  279,  108,  108,  279,  279,
      108,  279,  279,  108,  117,  279,  279,  279,  279,  279,
      117,  279,  279,  117,  279,  279,  117,  234,  279,  279,
      279,  234,  279,  279,  279,  234,  279,  279,  279,  234,
      254,  279,  279,  254,  279,  279,  279,  279,  254,  279,
      279,  279,  254,  269,  279,  279,  279,  269,  279,  269,

      279,  269,  279,  279,  279,  269,  272,  279,  279,  279,
      272,  279,  272,  279,  272,  279,  279,  279,  272,  278,
      279,  279,  279,  278,  279,  278,  279,  278,  279,  279,
      279,  278,    3,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279
    } ;

static yyconst short int yy_chk[1175] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,   11,   12,   95,   12,   11,   13,   14,   13,
       14,   15,   20,   14,   95,   15,   20,   21,   22,   21,
       23,   22,    6,    6,   23,    6,  164,   29,    6,    6,
        9,    9,   17,    9,   29,   30,    9,    9,   31,    9,
      164,    9,   32,   30,   31,    9,   32,   33,    9,   35,
       34,   33,   35,   17,   17,   38,   17,   34,   37,   17,

       17,   36,   36,   38,   40,   37,  303,    9,    9,   10,
       10,   40,   10,   33,  267,   10,   10,   39,   10,   41,
       10,   39,   41,   54,   10,   55,   56,   10,   54,   56,
       57,   55,   58,   61,   61,   10,   58,   57,   62,   63,
       62,   67,   67,  265,   63,   65,   10,   10,   25,   25,
       64,   25,   65,  128,   25,   25,   64,   25,  128,   25,
       25,   25,   78,   25,   78,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   79,   25,   25,   26,   26,   86,
       26,  263,   80,   26,   26,   86,   26,   89,   26,   80,

       82,   82,   26,   87,   89,   26,   87,   88,  100,   88,
       79,  100,  142,  101,   82,   82,   82,  145,  116,  142,
       79,  116,  145,  110,   26,   26,   53,   53,  262,   53,
      108,  110,   53,   53,  108,   53,  110,   53,  108,   53,
      101,  103,  103,  108,   53,  105,  105,  115,  136,  101,
      261,  115,  136,  147,  117,  103,  103,  103,  147,  105,
      105,  105,  117,   53,   53,   60,   60,  117,   60,  160,
      160,   60,   60,  115,   60,  259,   60,   60,  129,  134,
       60,  131,  129,   60,  144,  131,  129,  134,  144,  131,
      177,  129,  134,  135,  131,  177,  146,  135,  231,  149,

      168,  135,   60,   60,   66,   66,  135,   66,  258,  170,
       66,   66,  138,   66,  231,   66,   66,  257,  139,   66,
      138,  140,   66,  135,  155,  138,  139,  256,  155,  140,
      214,  139,  146,  166,  140,  149,  168,  166,  255,  227,
      157,   66,   66,   74,   74,  170,   74,  158,  157,   74,
       74,  140,   74,  157,   74,  158,   74,  162,  162,  196,
      158,   74,  178,  178,  196,  251,  214,  227,  229,  213,
      184,  162,  162,  162,  213,  250,  178,  178,  178,  163,
       74,   74,   76,   76,  184,   76,  249,  163,   76,   76,
      183,   76,  163,   76,  208,   76,  180,  180,  183,  208,

       76,  194,  208,  183,  229,  194,  248,  194,  163,  194,
      180,  180,  180,  194,  194,  183,  247,  240,  215,   76,
       76,   83,   83,  215,   83,  239,  222,   83,   83,  197,
       83,  222,   83,  188,  188,  224,   83,  197,  216,   83,
      224,  197,  197,  224,  217,  226,  216,  188,  188,  188,
      226,  216,  217,  226,  238,  237,  236,  217,   83,   83,
       85,   85,  280,   85,  282,  232,   85,   85,   85,   85,
      232,   85,   85,   85,  280,   85,  282,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,  233,   85,   85,   90,

       90,  228,   90,  242,  234,   90,   90,  242,   90,  234,
       90,  200,  200,  241,   90,  202,  202,   90,  241,  243,
      253,  241,  245,  223,  253,  200,  200,  200,  221,  202,
      202,  202,  233,  220,  219,  243,   90,   90,   99,   99,
      225,   99,  210,  241,   99,   99,  210,   99,  210,   99,
      210,   99,  252,  218,  212,  210,   99,  252,  245,  254,
      252,  225,  225,  254,  225,  264,  270,  225,  225,  235,
      264,  211,  209,  264,  260,   99,   99,  114,  114,  260,
      114,  252,  260,  114,  114,  207,  114,  206,  114,  284,
      235,  235,  114,  235,  270,  114,  235,  235,  266,  260,

      205,  284,  204,  266,  268,  114,  266,  203,  286,  268,
      266,  201,  268,  269,  114,  114,  118,  118,  269,  118,
      286,  269,  118,  118,  271,  118,  199,  118,  272,  271,
      273,  118,  271,  272,  118,  273,  272,  198,  273,  291,
      274,  277,  275,  195,  118,  274,  277,  275,  274,  277,
      275,  291,  193,  118,  118,  124,  124,  192,  124,  191,
      273,  124,  124,  190,  124,  293,  124,  275,  124,  274,
      276,  278,  294,  124,  299,  276,  278,  293,  276,  278,
      189,  187,  276,  301,  294,  302,  299,  186,  305,  310,
      315,  317,  124,  124,  130,  301,  182,  302,  181,  130,

      305,  310,  315,  317,  179,  176,  175,  174,  173,  172,
      167,  165,  161,  154,  153,  130,  130,  152,  130,  151,
      150,  130,  130,  132,  132,  143,  132,  132,  141,  132,
      132,  137,  132,  133,  132,  127,  132,  126,  125,  123,
      122,  132,  121,  120,  119,  111,  109,  107,  106,  104,
       98,   97,   94,   93,   92,   91,   84,   81,   75,   73,
      132,  132,  156,  156,   72,  156,  156,   71,  156,  156,
       70,  156,   69,  156,   68,  156,   59,   52,   51,   50,
      156,   49,   48,   47,   42,   28,   27,   24,   19,   18,
       16,    8,    7,    3,    0,    0,    0,    0,    0,  156,

      156,  281,  281,  281,    0,    0,  281,    0,    0,  281,
        0,    0,  281,  281,  283,  283,  283,    0,    0,  283,
        0,    0,  283,  283,    0,    0,  283,  285,  285,  285,
        0,    0,  285,    0,    0,  285,    0,    0,  285,  285,
      287,  287,    0,    0,    0,    0,    0,    0,  287,    0,
      287,  287,  287,  288,  288,  288,    0,    0,  288,    0,
        0,    0,    0,    0,  288,  288,  289,  289,  289,    0,
        0,  289,    0,    0,    0,    0,    0,  289,  289,  290,
      290,  290,    0,    0,  290,    0,    0,  290,  290,    0,
        0,  290,  292,    0,    0,  292,    0,    0,  292,    0,

      292,  292,    0,    0,  292,  295,    0,    0,    0,    0,
        0,  295,    0,  295,  295,    0,    0,  295,  296,    0,
        0,    0,  296,    0,    0,    0,  296,    0,    0,    0,
      296,  297,  297,  297,  297,    0,  297,    0,    0,  297,
      297,    0,    0,  297,  298,    0,    0,    0,    0,    0,
      298,    0,  298,  298,    0,    0,  298,  300,  300,    0,
        0,    0,    0,    0,    0,  300,    0,  300,  300,  300,
      304,  304,    0,    0,    0,    0,    0,    0,  304,    0,
      304,  304,  304,  306,    0,    0,  306,    0,  306,  306,
        0,  306,  306,    0,    0,  306,  307,    0,    0,    0,

      307,    0,    0,    0,  307,    0,    0,    0,  307,  308,
        0,    0,    0,    0,    0,  308,    0,  308,  308,    0,
        0,  308,  309,  309,    0,    0,    0,  309,  311,    0,
        0,    0,  311,    0,  311,    0,  311,    0,    0,    0,
      311,  312,    0,    0,  312,    0,  312,  312,    0,    0,
      312,    0,    0,  312,  313,    0,    0,    0,    0,    0,
      313,    0,    0,  313,    0,    0,  313,  314,    0,    0,
        0,  314,    0,    0,    0,  314,    0,    0,    0,  314,
      316,    0,    0,  316,    0,    0,    0,    0,  316,    0,
        0,    0,  316,  318,    0,    0,    0,  318,    0,  318,

        0,  318,    0,    0,    0,  318,  319,    0,    0,    0,
      319,    0,  319,    0,  319,    0,    0,    0,  319,  320,
        0,    0,    0,  320,    0,  320,    0,  320,    0,    0,
        0,  320,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  279
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "Compiler.l"
#define INITIAL 0
#line 2 "Compiler.l"
	int var = 0, mvar = 0, func = 0, loop = 0, if_else = 0;
	int start_brace;
#line 723 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 24 "Compiler.l"


#line 877 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 280 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1133 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 26 "Compiler.l"
{printf("Header File: %s\n", yytext);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 28 "Compiler.l"
{printf("Comment: %s\n", yytext);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 30 "Compiler.l"
{
	var++;
	printf("Variable Declaration: %s\n",yytext);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 35 "Compiler.l"
{
	mvar++;
	printf("Multiple Variable Declaration:\n    %s\n",yytext);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 40 "Compiler.l"
{
	func++;
	start_brace++;
	printf("Function:\n    %s\n", yytext);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 46 "Compiler.l"
{
	printf("Arithmatic/Bitwise Operation: %s\n", yytext);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 50 "Compiler.l"
{
	start_brace++, if_else++;
	printf("IF condition:\n    %s\n", yytext);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 54 "Compiler.l"
{
	start_brace++;
	printf("ELSE IF condition:\n    %s\n", yytext);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 58 "Compiler.l"
{
	start_brace++;
	printf("Else condition:\n    %s\n", yytext);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 63 "Compiler.l"
{
	start_brace++, loop++;
	printf("While Loop Starts:\n    %s\n", yytext);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 68 "Compiler.l"
{
	if(start_brace > 0) {
		if(yytext[0] == '}') start_brace--, printf("    }");
		else printf("%s", yytext);	
	}
	else {
		printf("Unexpected %s;\n", yytext); 
	}
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 79 "Compiler.l"
ECHO;
	YY_BREAK
#line 1052 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 280 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 280 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 279);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 79 "Compiler.l"


; int yywrap(){}

; int main()
; {
; 	freopen("input.txt", "r", stdin);
; 	freopen("output.txt", "w", stdout);

; 	yylex();

; 	printf("\n\n");
; 	printf("variables = %d\n", var);
; 	printf("multiple variables = %d\n", mvar);
; 	printf("functions = %d\n", func);
; 	printf("loop = %d\n", loop);
; 	printf("IF-Else = %d\n", if_else);	

; 	return 0;
; }

